import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./redux/provider";
import AuthCheck from './component/AuthCheck';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "T.A.P. Faucet Control Platform",
  description: "Generated by MITLAB",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <AuthCheck /> {/* 當沒有access token會強制路由到login頁面 */}
          {children}
        </Provider>
      </body>
    </html>
  );
}
